"""empty message

Revision ID: 42ce40fee548
Revises: e96b43ef1ac3
Create Date: 2025-05-22 10:17:16.939458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ce40fee548'
down_revision = 'e96b43ef1ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_people',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'people_id')
    )
    op.create_table('film_planets',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'planet_id')
    )
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('films_homeworld_key', type_='unique')
        batch_op.drop_column('homeworld')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_constraint('people_homeworld_key', type_='unique')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_unique_constraint('people_homeworld_key', ['homeworld'])
        batch_op.alter_column('gender',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('films_homeworld_key', ['homeworld'])
        batch_op.drop_column('release_date')

    op.drop_table('film_planets')
    op.drop_table('film_people')
    # ### end Alembic commands ###
